spring:
#  main: плохая альтернатива классу CustomSecurityConfig
#    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/webshopecorn
    password: 123
    username: postgres
  flyway:
    baseline-on-migrate: true


