spring:
#  main: плохая альтернатива классу CustomSecurityConfig
#    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/webshopecorn
    password: 123
    username: postgres
    hikari:
      auto-commit: false

  flyway:
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


